version: '1'

services:
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456789
    volumes:
      - ./data:/data/db
